-- Script pour le module de pointage (présence des employés)
-- A exécuter dans votre base de données Oracle

-- 1. Séquence pour les IDs
CREATE SEQUENCE POINTAGE_SEQ START WITH 1 INCREMENT BY 1;

-- 2. Table POINTAGE
CREATE TABLE POINTAGE (
    ID_POINTAGE     NUMBER PRIMARY KEY,
    SK_UTILISATEUR  NUMBER NOT NULL,
    DATE_POINTAGE   DATE NOT NULL,
    HEURE_ARRIVEE   TIMESTAMP,
    HEURE_DEPART    TIMESTAMP,
    STATUT          VARCHAR2(20),
    SOURCE          VARCHAR2(10),   -- 'AUTO' ou 'MANUEL'
    COMMENTAIRE     VARCHAR2(1000),
    CONSTRAINT FK_POINTAGE_USER FOREIGN KEY (SK_UTILISATEUR)
        REFERENCES B_UTILISATEURS(SK_UTILISATEUR),
    CONSTRAINT CHK_POINTAGE_STATUT CHECK (STATUT IN ('PRESENT', 'RETARD', 'ABSENT'))
);

-- Index pour accélérer les recherches par employé et par date
CREATE INDEX IDX_POINTAGE_USER ON POINTAGE(SK_UTILISATEUR);
CREATE INDEX IDX_POINTAGE_DATE ON POINTAGE(DATE_POINTAGE);

COMMIT;

-- 3. Vue décisionnelle pour Power BI : analyse de la présence
CREATE OR REPLACE VIEW V_BI_POINTAGE AS
SELECT
    P.ID_POINTAGE,
    P.DATE_POINTAGE,
    TO_CHAR(P.DATE_POINTAGE, 'YYYY-MM') AS ANNEE_MOIS,
    U.LIBELLE_UTILISATEUR AS NOM_EMPLOYE,
    A.LIBELLE_AGENCE AS NOM_AGENCE,
    A.DISTRICT AS DISTRICT_AGENCE,
    P.STATUT,
    CASE WHEN P.STATUT IN ('PRESENT', 'RETARD') THEN 1 ELSE 0 END AS EST_PRESENT,
    CASE WHEN P.STATUT = 'RETARD' THEN 1 ELSE 0 END AS EST_RETARD,
    CASE WHEN P.STATUT = 'ABSENT' THEN 1 ELSE 0 END AS EST_ABSENT
FROM
    POINTAGE P
LEFT JOIN B_UTILISATEURS U ON P.SK_UTILISATEUR = U.SK_UTILISATEUR
LEFT JOIN AGENCE A ON U.SK_AGENCE = A.SK_AGENCE;

COMMENT ON COLUMN V_BI_POINTAGE.EST_PRESENT IS 'Indicateur de présence (présent ou en retard)';
COMMENT ON COLUMN V_BI_POINTAGE.ANNEE_MOIS IS 'Période au format YYYY-MM pour le suivi mensuel';
