-- Scripts pour les nouvelles fonctionnalités d'approbation (Clients et Employés)
-- A exécuter dans votre base de données Oracle

-- 1. Table DEMANDE_CLIENT
CREATE SEQUENCE DEMANDE_CLIENT_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE DEMANDE_CLIENT (
    ID_DEMANDE NUMBER PRIMARY KEY,
    ID_DIRECTEUR NUMBER NOT NULL,
    NOM_CLIENT VARCHAR2(200) NOT NULL,
    PRENOM_CLIENT VARCHAR2(200) NOT NULL,
    SEXE VARCHAR2(1),
    TYPE_CLIENT VARCHAR2(50),
    SECTEUR_ACTIVITE VARCHAR2(200),
    SK_AGENCE NUMBER,
    SK_GESTIONNAIRE NUMBER,
    STATUT VARCHAR2(20) DEFAULT 'EN_ATTENTE',
    DATE_CREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    COMMENTAIRE_ADMIN VARCHAR2(1000),
    CONSTRAINT FK_DIR_CLIENT FOREIGN KEY (ID_DIRECTEUR) REFERENCES B_UTILISATEURS(SK_UTILISATEUR)
);

-- 2. Table DEMANDE_EMPLOYE
-- Note: Si la table existe déjà, ignorez cette partie ou adaptez-là
CREATE SEQUENCE DEMANDE_EMPLOYE_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE DEMANDE_EMPLOYE (
    ID_DEMANDE NUMBER PRIMARY KEY,
    ID_DIRECTEUR NUMBER NOT NULL,
    NOM VARCHAR2(100) NOT NULL,
    PRENOM VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(200),
    MATRICULE VARCHAR2(50),
    SK_AGENCE NUMBER,
    ROLE_PREVU NUMBER,
    STATUT VARCHAR2(20) DEFAULT 'EN_ATTENTE',
    DATE_CREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    COMMENTAIRE_ADMIN VARCHAR2(1000),
    CONSTRAINT FK_DIR_EMP FOREIGN KEY (ID_DIRECTEUR) REFERENCES B_UTILISATEURS(SK_UTILISATEUR)
);

COMMIT;
