-- Script pour le workflow de demande de modification des données employés
-- A exécuter dans votre base de données Oracle

-- 1. Séquence pour les IDs
CREATE SEQUENCE DEMANDE_MODIF_SEQ START WITH 1 INCREMENT BY 1;

-- 2. Table DEMANDES_MODIFICATION
CREATE TABLE DEMANDES_MODIFICATION (
    ID NUMBER PRIMARY KEY,
    ID_USER NUMBER NOT NULL,
    CHAMP VARCHAR2(20) NOT NULL, -- 'nom' ou 'email'
    ANCIENNE_VAL VARCHAR2(200),
    NOUVELLE_VAL VARCHAR2(200) NOT NULL,
    STATUT VARCHAR2(20) DEFAULT 'EN_ATTENTE', -- 'EN_ATTENTE', 'EN_COURS', 'REFUSE', 'EFFECTUE'
    DATE_DEMANDE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATE_DECISION TIMESTAMP,
    COMMENTAIRE VARCHAR2(1000),
    CONSTRAINT FK_MODIF_USER FOREIGN KEY (ID_USER) REFERENCES B_UTILISATEURS(SK_UTILISATEUR),
    CONSTRAINT CHK_MODIF_CHAMP CHECK (CHAMP IN ('nom', 'email', 'feature')),
    CONSTRAINT CHK_MODIF_STATUT CHECK (STATUT IN ('EN_ATTENTE', 'EN_COURS', 'REFUSE', 'EFFECTUE'))
);

-- Index pour accélérer les recherches par utilisateur
CREATE INDEX IDX_MODIF_USER ON DEMANDES_MODIFICATION(ID_USER);

COMMIT;
