-- Vue pour l'analyse des performances et objectifs (Power BI)
-- Regroupe les indicateurs de production par période et agence

CREATE OR REPLACE VIEW V_BI_OBJECTIFS AS
SELECT 
    O.ID_OBJECTIF,
    O.ANNEE_MOIS,
    A.LIBELLE_AGENCE AS NOM_AGENCE,
    U.LIBELLE_UTILISATEUR AS NOM_GESTIONNAIRE,
    O.SITUATION_ADMINISTRATIVE,
    -- Indicateurs de production
    (NVL(O.SOUSCRIPTION_COMPTE_CHEQUES_OA, 0) + 
     NVL(O.SOUSCRIPTION_COMPTE_EPARGNES_OA, 0) + 
     NVL(O.SOUSCRIPTION_COMPTE_COURANTS_OA, 0)) AS TOTAL_OUVERTURE_COMPTES,
    NVL(O.PRODUCTION_CREDITS_CONSO_OA, 0) AS CREDITS_CONSO,
    NVL(O.PRODUCTION_CREDITS_IMMO_OA, 0) AS CREDITS_IMMO,
    NVL(O.PRODUCTION_CREDITS_INVESTISSEMENT_OA, 0) AS CREDITS_INVEST,
    NVL(O.SOUSCRIPTION_CARTES_UNITE_OA, 0) AS CARTES_COMMANDES,
    -- Collecte
    NVL(O.EPARGNE_ADD_OA, 0) AS COLLECTE_EPARGNE
FROM 
    B_OBJECTIF O
LEFT JOIN 
    AGENCE A ON O.SK_AGENCE = A.SK_AGENCE
LEFT JOIN 
    B_UTILISATEURS U ON O.SK_UTILISATEUR = U.SK_UTILISATEUR;

COMMENT ON COLUMN V_BI_OBJECTIFS.TOTAL_OUVERTURE_COMPTES IS 'Somme des comptes chèques, épargnes et courants';
COMMENT ON COLUMN V_BI_OBJECTIFS.ANNEE_MOIS IS 'Période au format YYYY-MM ou similaire';
